version: '3.4'

services:
  mini_gw_proxy:
    build: 
      context: .
      target: mini_gw_proxy
    container_name: mini_gw_proxy
    command:
      - /opt/services/mini-gateway/proxy/proxy-entrypoint.sh

  mini_gw_internal_api:
    build: 
      context: .
      target: mini_gw_internal_API
    container_name: mini_gw_internal_API
    command:
        - /opt/services/mini-gateway/internal_API_server/internal-API-entrypoint.sh
    ipc: host
    volumes:
      - shared_volume:/opt/services/mini-gateway/shared

  mini_gw_vendor_kakao:
    build: 
      context: .
      target: mini_gw_vendor_kakao
    container_name: mini_gw_vendor_kakao
    command:
        - /opt/services/mini-gateway/vendor-kakao/kakao-entrypoint.sh
    ipc: host
    volumes:
      - shared_volume:/opt/services/mini-gateway/shared
    
volumes:
  shared_volume:
