version: '3.4'

services:
  mini_gw_proxy:
    build: 
      context: .
      target: mini_gw_proxy
    container_name: mini_gw_proxy
    command:
      - /opt/services/mini-gw-proxy/proxy-entrypoint.sh

  mini_gw_internal_api:
    build: 
      context: .
      target: mini_gw_internal_API
    container_name: mini_gw_internal_API
    command:
        - /opt/services/mini-gw-proxy/internal-API-entrypoint.sh
