Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"

  config.vm.provision :shell, path: "boot-strap.sh"

  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: [".git/," "spike/", "third-party/", "build/"]
end
